name: CI
on:
  push:
    branches: [ feature/configure-antora ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: antora/antora:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
            antora antora-playbook.yml
            ls -l public
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          # workingDirectory: public
          command: pages publish --project-name=docs-fbc-com public
          apiToken: ${{ secrets.CF_API_TOKEN }} 
          accountId: ${{ secrets.CF_ACCOUNT_ID }}           