name: CI
on:
  push:
    branches: [ feature/configure-antora ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: antora/antora:latest
    steps:
      - uses: actions/checkout@v3
      - name: List Directories
        run: ls -la