name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-nd-publish:
    runs-on: ubuntu-latest
    container:
      image: antora/antora:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Antora
        run: antora antora-playbook.yml
      - name: Publish Antora
        uses: cloudflare/wrangler-action@2.0.0
        with:
          command: pages publish --project-name=docs-fbc-com --branch=main public
          apiToken: ${{ secrets.CF_API_TOKEN }} 
          accountId: ${{ secrets.CF_ACCOUNT_ID }}           